{% set name = "django-test-plus" %}
{% set version = "1.4.0" %}
{% set sha256 = "9c3ca75f9ebb0b72d0a16e98b6d80e94b3d0ff007be5fc946d16b423b808bf16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python  

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - factory_boy >=2.5.2

about:
  home: https://github.com/revsys/django-test-plus
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE' 
  summary: 'Useful additions to Django default TestCase'
  description: |
    Let's face it, writing tests isn't always fun. Part of the reason for that is all of the 
    boilerplate you end up writing. django-test-plus is an attempt to cut down on some of 
    that when writing Django tests. We guarantee it will increase the time before you get 
    carpal tunnel by at least 3 weeks!
  doc_url: http://django-test-plus.readthedocs.org/
  dev_url: https://github.com/revsys/django-test-plus

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
