{% set name = "django-test-plus" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-test-plus-{{ version }}.tar.gz
  sha256: 06488209a07dca60dc2bbeaeae5ce340d17344163e0b121709cdac7405c6d9ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pytest-django
    - pip
  run:
    - python >={{ python_min }}
    - django >=1.8

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/revsys/django-test-plus
  license: BSD-3-Clause
  license_family: BSD
  #license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license_file: LICENSE
  summary: 'Useful additions to Django default TestCase'
  description: |
    Let's face it, writing tests isn't always fun. Part of the reason for that is all of the 
    boilerplate you end up writing. django-test-plus is an attempt to cut down on some of 
    that when writing Django tests. We guarantee it will increase the time before you get 
    carpal tunnel by at least 3 weeks!
  doc_url: http://django-test-plus.readthedocs.org/
  dev_url: https://github.com/revsys/django-test-plus

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
