travis:
  secure:
    BINSTAR_TOKEN: rEb84exrZJlDE5SIA/qBlBaQ59PDwP4cc1UZmbeLZEcyYfFjIwyXHkzbWJeJ23Z6kl8ylc2/2ggC+7LTfresDuWLVymDUfoOVCExS1NX0uGmQzXi697GGicims8GGzOyOvea0VCNlqasEFMe91+U9dCmB2OnOKtlOejIRmuqU6eyT+Z92Fh3kuhOU2miX6FsECzEdlUMO1imAMwFxgC3K/mX3rxLB0ax/bB4ZVJie61vDNrdO8vqVA7GRPqQaIYEguVeBc2gPYsxyWDmxHcatBtdohMvEybmVYqYvIRMi6mEly/U5cGKX9LkoUIRp+xRuFtR+Xclgg2P4r/FupvSrBJvSR1XVIM5Z8HsLKcOPRNOYJTx1TPnIUfJeMxwiC9qSXaOdhFtmXuHhmoI4/Umd1/bzsZTN2dZB5no+CTWl+tBxHwWFD8JicONejONjh+PzDyAqCFz+uKqJOyy6mpjukzIkqjPGXJIYaiI4JmNu3D8wU6NMNTiewpRI7HlCkZIwJwv0VBQc0B4Aueut9NJLiGRmxLmdefPrPkBVluy+ga47wMLhOI7JfZpGzYr1IGGfWMmc7oFNJjxI7IgGLNtPs3Uk67gyunqcVReTHYDhhTjPfT4qP4KSvlDyE3KS1rJzZHA2S3vkftVgiU6mNQseNV00VxlQyCbsMyBxzAb//o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
