travis:
  secure:
    BINSTAR_TOKEN: OWEtdSkPb//+3xYynYJMMRnnetF+5EAvpsNS1xjVEfGGtFVps9JDtY0bIYX3J/HTOnKgdALxAkrwH+3yYl1lxlOd192auHZaOFptSjT4wHoDmdmDGen9NsRJjX4ByZehlhHq89ukIMhsDoVy+Z0gceBSjreeG30x6NQ0Gl91SptnMVJKH6PjhqgUSW+Z3Q83jNUMBSl9KuelMPBsMu9GXkD4cpIv4kO0olLxMyAl8FhzQJPauFAxaVSNccP0icgZUkJlrEYsNZiAuOfkd4bRokcH5rYZ+ovNnHMJ4auyYE1ySQHtMlqHrh955VPGMzHzlAeTV5KNMniZZ0a1xtog71SOfWuV3Ow7bp0FjWW6jy2kpBzy0UmsBANSLlfoMBSPi7ljJi6Zwt+pnPUsmR/XB9UBiHZyyuq8+8X7SWCbRxSFdgt31zunStXl8yzRUr2ITjQpGDmtoCxw67V2v+Jl+OttT9wSKw7ve1J1sz1CDpQquMM6DY8C+6ximHgdEXTn5DRFrWZypMKrP20aoFve79MgQ5ihV8+mJC62HVicNusUpNqCxQpxpohcfjzJCZRuF3FepG2PiEkWljJXRrcmtO3jHllo3WQ2VUsFjDYILOz+m8sMnxvHuUN7AvESCVQ3DXwqKbXL3TmiPcQ5+8nCrDed14Lc8pbYf/2z0+k14ZE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
